### ISSUE TITLE
KeyError: '0_34'

### ISSUE THREAD

**Issue by BenxiaHu** [paulranum11/SPLiT-Seq_demultiplexing#11]

**Comment by paulranum11** [comment]
Hi Biohubx,

It seems like it is failing to read in the provided input .fastq files.
Please confirm that your input fastq's exist at the provided file location "
/snRNAseq/BC83_S8_R1.fastq"  Note that this would be an odd location to
keep your file... In your filename the leading "/" character indicates the
root directory of your entire system.  If you intend for the provided file
path to begin at the current working directory then use "./" or nothing as
the leading character.  If your file paths are correct then it seems like
this may be a disk space issue.  What is the available disk space on your
machine?  Also what is the available ram?

Another suggestion. If your files are large (not the small provided
examples) I suggest you increase your "minreadspercell = 10" to 200.

Hope this helps,
Paul

**Comment by biohubx** [comment]
that error has been resolved.
I got another error:
Traceback (most recent call last):
  File "InDevOptimizations/DemultiplexUsingBarcodes_New_V1.py", line 332, in <module>
    **readF_BC_UMI = barcodeRead(name = readsF[key].name, \
KeyError: '0_34'**
