### ISSUE TITLE
odd results

### ISSUE THREAD

**Issue by BenxiaHu** [paulranum11/SPLiT-Seq_demultiplexing#12]

**Comment by paulranum11** [comment]
Open the produced counts.tsv.gz file using a text editor or excel.  This file contains the list of genes and cells detected you will be able to see how many genes are detected.  It is possible you are not properly importing this table into Seurat.  

As these experiments are very complex with many things that can go wrong it is very difficult for me to help you without being able to look directly at the fastq files you are working with.  We still have no confirmation that your fastq files are in the correct format or contain the correct number of barcodes.  I also still don't know if you were able to work with the provided example fastq.  Furthermore we don't have confirmation that the barcodes used in your experiment are even the published split-seq barcodes provided for default use with this script.  All of these issues could reduce or totally eliminate the detection of any single-cell reads from your dataset leading to a small output file.

To continue helping you troubleshoot i need you to send me the first  5000 or so lines of your input Forward and Reverse fastq files.  I will be able to tell if they contain viable split-seq barcodes.
