### ISSUE TITLE
step 4 issue

### ISSUE THREAD

**Issue by BenxiaHu** [paulranum11/SPLiT-Seq_demultiplexing#13]
hello,
     when I ran splitseqdemultiplex, I find that the step 4 takes a long time.
     it seems that the step4 has been running 1 day:
Beginning STEP4: Extracting UMIs. Current time : **2021-05-03 06:45:57**.

Do you think it is fine?

**Comment by dumaatravaie** [comment]
Hi, I don't think so. I have been using this pipeline for a long time and for me the step 4 never took 24 hours !!!!! For a input data of around  80GB ( R1 and R2 ), it takes around 12/15 hours ( slower version ) for all the steps to finish completely. I feel that your input sequence file might have some kind of problem ....

**Comment by BenxiaHu** [comment]
the R1/2 is about 100G and 130G, respectively. 
I used the following arguments:
-n 16 -v merged -e 1 -m 10 \
     **-1 Round1_barcodes_new5.txt -2 Round2_barcodes_new4.txt -3 Round3_barcodes_new4.txt** \
     -f read1.fastq -r read2.fastq -o ../snRNAseq_output_merged -t 1000000 \
     -g 100000 -c true -a star -x ../mm10index
     -s "SAF ../mm10.saf"

the collaborator said "use the barcode in the below paper as reference". 
https://science.sciencemag.org/content/360/6385/176.

**Comment by dumaatravaie** [comment]
Evenfor input files of around 100G and 130G, the STEP4 should not take 1 day or more. The step 4 is not the most computationally intensive step of this pipeline. The pipeline may be slow in the case your machine has not enough memory and CPUs. Please check whether your machine has enough memory and CPU cores.

**Comment by BenxiaHu** [comment]
OK. 

the barcodes I used are correct, right?

**Comment by dumaatravaie** [comment]
The barcode in the paper are correct. But, You must check whether the barcode in the paper really correspond with the barcode of your input fastq file. If not, then there is problem with your input fastq file.

**Comment by paulranum11** [comment]
Hi Biohubx,

I have observed similar challenges with step 4 runtime for some datasets.  One setting change that will help a lot is to use a higher minimum read threshold like `-m 200` instead of `-m 10` That way the program wont have to spend time extracting the UMIs from reads assigned to low detection cells that will later be discarded anyway.  

There is actually an even better solution available which is to use the latest version of the software which has eliminated the UMI extraction step completely.  This version is accessible in the "python_only_tool" directory.  The input arguments are slightly different but quite similar.  The executable file is called `python_only_tool/splitseqdemultiplex_0.2.2.py`.

The long runtime for UMI finding does not mean that there is a problem with the tool or your input... but it will be faster to use the `python_only_tool`

**Comment by dumaatravaie** [comment]
Yes, i agree with @paulranum11

**Comment by BenxiaHu** [comment]
@paulranum11 
python_only_tool/splitseqdemultiplex_0.2.2.py does not generate expression matrix, right?
if I set m to a very high value, such as 20, does it will impact downstream results?

**Comment by paulranum11** [comment]
python_only_tool/splitseqdemultiplex_0.2.2.py **does** generate the expression matrix.  You have to think of the -m argument in the context of your downstream analysis in Seurat.  If in Seurat you do filtering to exclude cells, often you will set parameters to retain cells with between 100 and 10,000 genes detected.  A cell with 90 genes detected may have 150 unique UMIs (some UMIs may map to the same gene) detected but it will ultimately be eliminated from the analysis.  This is why i recommend setting a `-m` threshold of 200 (to drop any cells with fewer than 200 unique UMIs).  This speeds up the analysis and does not have a major impact on the results of the single-cell analysis.  It can also dramatically reduce the size of the output counts matrix file.

**Comment by BenxiaHu** [comment]
@paulranum11 
thanks，I am trying to run splitseqdemultiplex_0.2.2.py. I also set m and b to 200 and 100000, respectively.

**Comment by paulranum11** [comment]
@biohubx 
That sounds like it should perform well.  Also please remember to enter the actual length of **your** input fastqR file for the -l parameter.  To get this number you can run `wc -l path/to/your/fastqR.fastq`

**Comment by BenxiaHu** [comment]
thanks.
I set -l to 2233046588

**Comment by paulranum11** [comment]
Hi @biohubx,

I believe @dumaatravaie and I will both be curious to know if this completed successfully.  Can you let us know if it worked for you?

Thanks,
Paul

**Comment by dumaatravaie** [comment]
hi @paulranum11 , as i have been reading all the issues posted by @biohubx , i am also as curious as you. 
First @biohubx said he had 4/5 barcodes, then he said the gene/cell_barcode matrix or gene expression matrix is empty. Then he opened the issue about the problem with Step 4. But, I do not know whether he is talking about the same input files for all these issues or not ? 
                       Also, at least he should tell us the average length of his sequences in both of his R1 and R2 file as it seems he does not want ( **or may be he has some kind of constraints** ) to give you a small sample of his sequences to test ! 
                       I have great confidence on this pipeline. Even last week i ran it for the input sequences of a different species other then human/mouse. The pipeline worked as expected without any issue.

**Comment by BenxiaHu** [comment]
@paulranum11 
yes, when I set m to 200, the entire analysis was done whtin 15h. 

However, I made some changes to your codes. 
When I ran the main shell script, some python scripts can't be found. So I add the absolute path to these scripts. 
And you set result to the default output in your main shell script, but when I ran the main shell script, I set o to another output name, the main shell script reported an error" the result output file cannot find it. "

**Comment by biohubx** [comment]
> hi @paulranum11 , as i have been reading all the issues posted by @biohubx , i am also as curious as you.
> First @biohubx said he had 4/5 barcodes, then he said the gene/cell_barcode matrix or gene expression matrix is empty. Then he opened the issue about the problem with Step 4. But, I do not know whether he is talking about the same input files for all these issues or not ?
> Also, at least he should tell us the average length of his sequences in both of his R1 and R2 file as it seems he does not want ( **or may be he has some kind of constraints** ) to give you a small sample of his sequences to test !
> I have great confidence on this pipeline. Even last week i ran it for the input sequences of a different species other then human/mouse. The pipeline worked as expected without any issue.

**Comment by paulranum11** [comment]
Hi Biohubx, 

Thanks for letting us know about the output name issue with the shell script.  This should be fixed in the python-only version.  The shell versions are outdated at this point.  I plan to create a new "release" through github that archives the shell scripts as outdated versions and lists python only tool as the primary version.  I just need to finish packaging the python only tool into a "python package" format first.

As it sounds like you have this issue solved by running the python only version with `-m 200`, I am going to close this issue for now.
