### ISSUE TITLE
What are the recommended steps once demultiplexing is complete?

### ISSUE THREAD

**Issue by jeremymsimon** [paulranum11/SPLiT-Seq_demultiplexing#2]
It would be helpful to describe what steps are recommended once the FASTQs are separated by cell. The SPLiT-seq paper utilizes one of the Drop-seq tools (TagReadWithGeneExon), followed by Starcode to collapse UMIs of aligned reads that were within 1 nt mismatch of another UMI. They then don't describe how they generated their final cell x gene expression matrix, but I assume it's the DigitalExpression tool from the Drop-seq toolkit as well. 

I'm trying to figure out how best to connect the dots from the output of your method to those steps, or if some other approach is better. 

Any advice would be appreciated!

**Comment by paulranum11** [comment]
Thanks for this suggestion. I agree that it would be helpful to many users to add the steps to generate the single-cell counts matrix.  The steps I would recommend are: 1 align each .fastq in the results_UMI folder with STAR. 2 use UMI-tools “dedup” to collapse PCR duplicates in each .bam and get counts. 3 merge the counts column from each cell (using basic python, bash or R functionality) to create the single cell counts matrix. Please note that there are many ways to do this and the steps I have suggested are simply the steps I am most familiar with.

I will work on implementing these steps in an update to SPLiT-Seq_Demultiplexing.  I hope this tool is helpful to you.

**Comment by jeremymsimon** [comment]
Thanks, that's helpful. Thoughts on the UMI corrections that something like dropEst performs?

**Comment by paulranum11** [comment]
DropEst looks like it should have better accuracy than some of the older UMI correction methods.  At first glance it should be possible to implement this type of correction.  I'll post updates to this issue as i begin to implement alignment, UMI correction, and counts matrix generation steps.  DropEst lists support for SPLiT-Seq have you tried demultiplexing using their pipeline?

**Comment by jeremymsimon** [comment]
I have tried it, but I reported an issue with it not properly tagging the FASTQs. The developer is apparently traveling, so it is currently unresolved.

I've been working on my own pipeline where I would do the following:

1. Demultiplex with this tool
2. Modify the results-umi/*.fq headers to embed the barcode and UMI sequence in the same format that dropEst uses
3. Run only one alignment job with STAR, where I pass the barcodes as read groups- that way it saves on alignment overhead and produces one BAM file rather than _Ncells_ BAM files. The read names also contain barcode/umi sequence (required for step 4). I would recommend implementing your alignment this way too if possible, since spawning 20k STAR alignments would needlessly burn through a lot of memory. A user could always split the combined BAM using `bamtools -split` by the RG. _*edit: Probably need to concatenate the FASTQs first, otherwise I hit the linux limit on number of arguments in a command_
4. Run dropEst

I can get dropEst to make a proper _cells x genes_ matrix using this approach and the test data from your repo, but only if I use `dropest -u [...]` rather than dropEstR's UMI correction methods. It also needs `-m` and `-M` both _disabled_. Those other UMI correction methods implemented in their R package require that the BAM file contains barcodes, UMIs, barcode qualities, and UMI qualities all embedded as tags (like 10x output). This tool/UMI-tools doesn't extract those quality scores, so it would be _doable_ to accomplish that but not necessarily trivial.

This approach would, however, skip the PCR deduplication step you recommended above. UMI-tools could do it on a single BAM like I'd be making using the `--per-cell` option, but would require barcodes etc tagged in yet a different way in the BAM file.

**Comment by paulranum11** [comment]
I added support for kallisto, a very fast pseudo-alignment strategy, that facilitates expression quantification and UMI correction.  The output generated are the components of a expression matrix (counts matrix, column names (Cell IDs), and rownames (transcript equivalence classes) that can be loaded into R and analyzed with popular tools like Seurat.  Take a look and see if this would fit your use case...  The one caveat is that in this implementation kallisto outputs "transcript compatibility counts" not reads per gene or reads per transcript.  However these equivalence classes can be mapped back to gene and transcript IDs using output generated by this tool.

The forthcoming STAR based strategy will output gene level counts but it will be much much slower. 

I would value any feedback you might have on this implementation.  Thanks!

**Comment by paulranum11** [comment]
I implemented support for a single output .fastq file in which reads are annotated with their cell ID and UMI barcodes.  This facilitates alignment of a single .fastq file. After alignment, counts per cell per gene are computed using FeatureCounts and UMIs are collapsed using UMI-Tools.  The result is a genes by cells UMI counts matrix.
